# Generated by Django 2.1.3 on 2019-02-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'male'), (0, 'female')], default=1),
            preserve_default=False,
        ),
    ]
