# Generated by Django 2.1.3 on 2019-02-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190204_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'male'), (0, 'female')], null=True),
        ),
    ]
