# Generated by Django 2.1.2 on 2018-12-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181219_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название'),
        ),
    ]
