# Generated by Django 2.1.2 on 2018-12-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foto',
            field=models.ImageField(blank=True, upload_to='product/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='subcatalog',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Catalog'),
        ),
    ]
