# Generated by Django 2.1.3 on 2019-03-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewCountry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='newcity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='load.NewCountry'),
        ),
    ]
