# Generated by Django 2.1.3 on 2019-03-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Стоимость')),
                ('length', models.SmallIntegerField(verbose_name='Объем')),
                ('author', models.ManyToManyField(related_name='book_author', to='book.Author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.SmallIntegerField(choices=[(1, 'Комедия'), (2, 'Фэнтези'), (3, 'Фантастика'), (4, 'Приключение'), (5, 'Детектив'), (6, 'Драма'), (7, 'Публицистика')], verbose_name='Жанр')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='genre_book', to='book.Genre'),
        ),
        migrations.AddField(
            model_name='author',
            name='owner',
            field=models.ManyToManyField(related_name='owner_book', to='book.Book'),
        ),
    ]
