# Generated by Django 2.1.3 on 2019-03-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Издательство'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='copy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='copy_book', to='book.Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='copy',
            field=models.CharField(default='', max_length=30, verbose_name='Издательство'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.SmallIntegerField(choices=[(1, 'Комедия'), (2, 'Фэнтези'), (3, 'Фантастика'), (4, 'Приключение'), (5, 'Детектив'), (6, 'Драма'), (7, 'Публицистика')], verbose_name='Жанр'),
        ),
    ]
